### ISSUE TITLE
発表者募集

### ISSUE THREAD

**Issue by nqounet** [kansai-pm/issues#4]
第16回ミーティングで発表していただける方です。
（募集は締め切りました）
## 発表者

@azumakuniyuki 「PerlモジュールをRubyに移植するときに落ちた穴々」 20分
@sago35 「サンモクを通して学んだ話」 20分
@xtetsuji 「（仮）WordPress の運用を改善する Perl」10分
@papix 「（仮）PerlのWebApp開発におけるの新たなスタンダード〜Aniki+Amon2〜」 10分
@karupanerura 「Time::Moment + Time::Strptime = :muscle:」 20分

**Comment by azumakuniyuki** [comment]
タイトルは未だ決めていませんが、PerlモジュールをRubyに移植した(三月には完了してる筈)ので、そのあたりで人様の役に立ちそうな話をしようかと思っています。

**Comment by sago35** [comment]
社内で、 [PerlNabe-Sanmoku](https://github.com/sago35/PerlNabe-Sanmoku) を使った勉強会というかプログラムなイベントしたのでそのネタか、何か考えます。
時期的には新ネタ考えたいところ。

**Comment by nqounet** [comment]
@azumakuniyuki :+1: 
@sago35 :+1: 
ありがとうございます :star2: 
必要な時間（10分以上40分までで10分単位）をお知らせください。

**Comment by sago35** [comment]
とりあえず20分でお願いします。

**Comment by nqounet** [comment]
@sago35 :ok_woman:

**Comment by xtetsuji** [comment]
構想段階ではありますが「WordPress の運用を改善する Perl」といったタイトルでトークしたいです。

今のところですが、時間は10分希望です。

**Comment by papix** [comment]
まだ構想段階ですが, ｢PerlのWebApp開発におけるの新たなスタンダード〜Aniki+Amon2〜｣というタイトルでなんか発表したいです. 時間は10分程度でお願いします.

**Comment by nqounet** [comment]
@xtetsuji :ok_woman: 
@papix :ok_woman: 
ありがとうございます。
よろしくお願い申し上げます。

**Comment by azumakuniyuki** [comment]
@nqounet すいません、予定時間の連絡が遅くなってしまいました。時間は20分でお願いいたします。もしも他の発表者が増えてきたら10分に削って頂いて結構ですのでよろしくお願いいたします。

**Comment by nqounet** [comment]
@azumakuniyuki :ok_woman: 
ありがとうございます。

**Comment by sago35** [comment]
@nqounet 同じく、他の発表者が増えてきたら、10分に削っていただいてOKです。

**Comment by nqounet** [comment]
@sago35 :ok_woman: 
ありがとうございます。
今のところ、削る心配はないと思います。

**Comment by karupanerura** [comment]
@nqounet 「Time::Moment + Time::Strptime = :muscle:」のタイトルでしゃべりたいです。
20min ~ 10minくらいで空いている枠があれば発表させて頂ければとおもいます。

**Comment by nqounet** [comment]
@karupanerura :ok_woman: 
ありがとうございます。
ひとまず20分で確保します。

**Comment by nqounet** [comment]
締め切ります。
発表タイトルが未定の方は決まったらお知らせください。

**Comment by azumakuniyuki** [comment]
@nqounet タイトル未定のままでした、遅くなってすいません。「PerlモジュールをRubyに移植するときに落ちた穴々」でお願いします。

**Comment by sago35** [comment]
@nqounet 「サンモクを通して学んだ話」でお願いします。遅くなってすみませんでした。

**Comment by nqounet** [comment]
@azumakuniyuki :ok_woman: 
@sago35 :ok_woman: 
ありがとうございます。
反映しておきます
